language: java
jdk:
  - openjdk11

branches:
  only:
    - master

before_script:
  - cd backend
  - cd project
  - chmod +x gradlew

# Travis CI 서버의 HOME
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r algohub-webservice *
  - mkdir -p deploy
  - mv algohub-webservice.zip deploy/algohub-webservice.zip

deploy
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
   
    secret_access_key: $AWS_SECRET_KEY

    bucket: algohub-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - fkam12@naver.com